[project]
name = "feedhound"
version = "0.1.0"
description = ""
authors = [
    {name = "NumiViX", email = "yakhin.v.r@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.12"

[tool.pytest.ini_options]
addopts = "-ra"
